package com.example.zomatoapp.RestrauntApi

data class RestaurantX(
    val r: R? = null ,
    val all_reviews: AllReviews? = null ,
    val all_reviews_count: Int? = null ,
    val apikey: String? = null ,
    val average_cost_for_two: Int? = null ,
    val book_again_url: String? = null ,
    val book_form_web_view_url: String? = null ,
    val cuisines: String? = null ,
    val currency: String? = null ,
    val deeplink: String? = null ,
    val establishment: List<String>? = null ,
    val establishment_types: List<Any>? = null ,
    val events_url: String? = null ,
    val featured_image: String? = null ,
    val has_online_delivery: Int? = null ,
    val has_table_booking: Int? = null ,
    val highlights: List<String>? = null ,
    val id: String? = null ,
    val include_bogo_offers: Boolean? = null ,
    val is_book_form_web_view: Int? = null ,
    val is_delivering_now: Int? = null ,
    val is_table_reservation_supported: Int? = null ,
    val is_zomato_book_res: Int? = null ,
    val location: Location? = null ,
    val medio_provider: Boolean? = null ,
    val menu_url: String? = null ,
    val mezzo_provider: String? = null ,
    val name: String? = null ,
    val offers: List<Any>? = null ,
    val opentable_support: Int? = null ,
    val order_deeplink: String? = null ,
    val order_url: String? = null ,
    val phone_numbers: String? = null ,
    val photo_count: Int? = null ,
    val photos_url: String? = null ,
    val price_range: Int? = null ,
    val store_type: String? = null ,
    val switch_to_order_menu: Int? = null ,
    val thumb: String? = null ,
    val timings: String? = null ,
    val url: String? = null ,
    val user_rating: UserRating? = null
)